// TODO Implement this library.// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      /*case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );*/
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
         throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBW2yZXtmFvPLj2dE1RWmPuhKRtah2kcFU",
    authDomain: "mhealth-4ba11.firebaseapp.com",
    projectId: "mhealth-4ba11",
    storageBucket: "mhealth-4ba11.appspot.com",
    messagingSenderId: "448485223874",
    appId: "1:448485223874:web:cd76a622216ca6991f7a5b"
  );

  /*static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAELXbG83O6fZyvbVk__sW8LhjGzQXVUWU',
    appId: '1:504805874781:android:55c9d3e844559e8fbbc1b4',
    messagingSenderId: '504805874781',
    projectId: 'medwell-6dfcf',
    storageBucket: 'medwell-6dfcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZaHpMSJawolpC0UlqjhXLdU2slEDwYu8',
    appId: '1:504805874781:ios:bdc7a787548eac4dbbc1b4',
    messagingSenderId: '504805874781',
    projectId: 'medwell-6dfcf',
    storageBucket: 'medwell-6dfcf.appspot.com',
    iosClientId:
        '504805874781-65229c0qcb87fa1sflq6bk08vp2336kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.medwell',
  );*/
}
